version: "3.3"
services:
  app:
    build: ../web-parawan

    ports:
      - 8085:8080
      - 9990:9990
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306

