<!DOCTYPE html>
<html>
  <body>
    <p>Main Menu</p>

    <nav>
      <ul>
        <li>
          <a href=make-reservation>Make reservation </a>
        </li>
        <li>
          <a href=cancel-reservation>Cancel reservation </a>
        </li>
        <li>
          <a href=find-place>Find place with additional requirements </a>
        </li>
        <li>
          <a href=item-management?hourFromForm=0>Number of items available for rent  </a>
        </li>
      </ul>
    </nav>

    <p><a href=hello-servlet>Go back to intro page </a></p>
  </body>
</html>