<!DOCTYPE html>
<html>
<body>
<p>Main Menu</p>

<nav>
    <ul>
        <li>
            <a href=/parawan/make-reservation>Make reservation </a>
        </li>
        <li>
            <a href=/parawan/cancel-reservation>Cancel reservation </a>
        </li>
        <li>
            <a href=/parawan/find-place>Find place with additional requirements </a>
        </li>
        <li>
            <a href=/parawan/item-management?hourFromForm=0>Number of items available for rent </a>
        </li>
        <li>
            <a href=/parawan/change-beach>Change actual working beach</a>
        </li>
    </ul>
</nav>

<p><a href=hello-servlet>Go back to intro page </a></p>
</body>
</html>