<div class="row">
    <div class="col">
                    <#list weather>
        <#items as weatherComponentsInList>
            ${weatherComponentsInList}<#sep><br></#sep>
        </#items>
                    </#list>

    </div>
    <div class="col">
                    <#list weather>
        <#items as weatherComponentsInList>
            ${weatherComponentsInList}<#sep><br></#sep>
        </#items>
                    </#list>

    </div>
    <div class="col">
                    <#list weather>
        <#items as weatherComponentsInList>
            ${weatherComponentsInList}<#sep><br></#sep>
        </#items>
                    </#list>

    </div>
    <div class="col">
                    <#list weather>
        <#items as weatherComponentsInList>
            ${weatherComponentsInList}<#sep><br></#sep>
        </#items>
                    </#list>

    </div>
    <div class="col">
                    <#list weather>
        <#items as weatherComponentsInList>
            ${weatherComponentsInList}<#sep><br></#sep>
        </#items>
                    </#list>

    </div>
    <div class="col">
                    <#list weather>
        <#items as weatherComponentsInList>
            ${weatherComponentsInList}<#sep><br></#sep>
        </#items>
                    </#list>

    </div>
    <div class="col">
                    <#list weather>
        <#items as weatherComponentsInList>
            ${weatherComponentsInList}<#sep><br></#sep>
        </#items>
                    </#list>

    </div>
    <div class="col">
                    <#list weather>
        <#items as weatherComponentsInList>
            ${weatherComponentsInList}<#sep><br></#sep>
        </#items>
                    </#list>

    </div>
    <div class="col">
                    <#list weather>
        <#items as weatherComponentsInList>
            ${weatherComponentsInList}<#sep><br></#sep>
        </#items>
                    </#list>

    </div>
</div>

